### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by g-tejas** [bqqbarbhg/bq_websocket#36]
`gcc ../bq_websocket.c ../bq_websocket_platform.c echo_client_pt.c -o echo -lpthread`

Been trying to compile the example test case, but i get the following missing symbol errors, any idea whats wrong?
![CleanShot 2024-04-12 at 11 25 01@2x](https://github.com/bqqbarbhg/bq_websocket/assets/76802638/d6079631-596d-4de2-bb8b-723ff3edbb1f)

**Comment by g-tejas** [comment]
Seems like the errors were CoreFoundation related, `gcc -DBQWS_PT_USE_CFSTREAM ../bq_websocket.c ../bq_websocket_platform.c ../test/fuzz/fuzz_protocol.c echo_client_pt.c -o echo -lpthread -framework CoreFoundation` fixed those but now i have 
![CleanShot 2024-04-12 at 11 44 07@2x](https://github.com/bqqbarbhg/bq_websocket/assets/76802638/93a957e5-2f98-4f93-a5a9-8542585df0ae)

**Comment by bqqbarbhg** [comment]
Sorry it's been ages since I've built this on macOS so I'm a bit hazy, looks like I was linking a larger project to the following frameworks:

```lua
links {
	"Foundation.framework",
	"Security.framework",
	"Metal.framework",
	"MetalKit.framework",
	"QuartzCore.framework",
	"CFNetwork.framework",
	"AudioToolbox.framework",
}
```

Just guessing, but I'd bet that `-framework CoreFoundation -framework CFNetwork -framework Security` would do the trick.

**Comment by g-tejas** [comment]
It did indeed solve it, thanks! Curious, what is the build system ur using in ur message, is it bazel?

**Comment by bqqbarbhg** [comment]
Nice! The build system is Premake 5: https://github.com/bqqbarbhg/spear/blob/master/premake5.lua?ts=4 (used in https://github.com/bqqbarbhg/spear/)

It worked quite well for a bunch of platforms, these days I'm tending towards CMake as it seems to be what _most_ people are using for C++.
